name: CI and CD data model

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - staging

jobs:
  retraining_model:
    runs-on: ubuntu-latest
    env:
      repo_token: ${{ secrets.GITHUBTOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install DVC
        run: pip install dvc

      - name: Pull data from DVC
        run: dvc pull

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Execute the training model
        run: python3 src/train_model.py

      - name: Generate report
        run: |
          echo "## Model metrics" > report.md
          echo "Model trained successfully with RandomForest." >> report.md
          pip install cml
          cml comment create report.md

  build_docker_image:
    needs: retraining_model
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps -q --filter "publish=8000") || true
            docker rm $(docker ps -aq --filter "publish=8000") || true
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
            docker pull gabrieldoin/supplement-api:dev
            docker run -d --name supplement-api -p 8000:8000 gabrieldoin/supplement-api:dev
